name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: set -o pipefail &&
          xcodebuild
          -scheme UIKitHelper
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
          build

  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: set -o pipefail &&
          xcodebuild
          -scheme UIKitHelper
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
          clean test
